const GET_VIDEO_INFO_LOADING = 'GET_VIDEO_INFO_LOADING';
const GET_VIDEO_INFO_SUCCESS = 'GET_VIDEO_INFO_SUCCESS';
const GET_VIDEO_LIST_LOADING = 'GET_VIDEO_LIST_LOADING';
const GET_VIDEO_LIST_SUCCESS = 'GET_VIDEO_LIST_SUCCESS';
const GET_VIDEO_REPLIES_LIST_LOADING = 'GET_VIDEO_REPLIES_LIST_LOADING';
const GET_VIDEO_REPLIES_LIST_SUCCESS = 'GET_VIDEO_REPLIES_LIST_SUCCESS';

export {
  GET_VIDEO_INFO_LOADING,
  GET_VIDEO_INFO_SUCCESS,
  GET_VIDEO_LIST_LOADING,
  GET_VIDEO_LIST_SUCCESS,
  GET_VIDEO_REPLIES_LIST_LOADING,
  GET_VIDEO_REPLIES_LIST_SUCCESS,
};
